### ISSUE TITLE
[feature] Reverse snapshots sequence and drag-drop

### ISSUE THREAD

**Issue by mikhailredis** [dai-shi/excalidraw-claymate#15]
Reverse snapshot sequence is really useful when you have a final drawing and go backward. Or add drag-drop functionality to move snapshots around.

**Comment by dai-shi** [comment]
cc @grant-davidson 

Yeah, we have lots of ideas for v2. I'm excited.

**Comment by grant-davidson** [comment]
@mikhailredis - The "Reverse Order" feature has now been released
