### ISSUE TITLE
Error when double-clicking a shape

### ISSUE THREAD

**Issue by ChristianDavis** [dai-shi/excalidraw-claymate#38]
Two circles joined with an arrow, and if you double clicking either of the circle shapes it throws this error:

`DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at D (https://dai-shi.github.io/excalidraw-claymate/static/js/main.88849190.chunk.js:1:11588)
    at https://dai-shi.github.io/excalidraw-claymate/static/js/main.88849190.chunk.js:1:13067
    at Lc (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:217002)
    at t.unstable_runWithPriority (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:234814)
    at Wo (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:156989)
    at Mc (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:216463)
    at https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:216374
    at N (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:233873)
    at MessagePort.x.port1.onmessage (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:232595)
al @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
fl @ react-dom.production.min.js:220
Cc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
_c @ react-dom.production.min.js:252
fc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Ko @ react-dom.production.min.js:123
Vo @ react-dom.production.min.js:122
Lc @ react-dom.production.min.js:263
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Mc @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
N @ scheduler.production.min.js:16
x.port1.onmessage @ scheduler.production.min.js:12
scheduler.production.min.js:12 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at D (https://dai-shi.github.io/excalidraw-claymate/static/js/main.88849190.chunk.js:1:11588)
    at https://dai-shi.github.io/excalidraw-claymate/static/js/main.88849190.chunk.js:1:13067
    at Lc (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:217002)
    at t.unstable_runWithPriority (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:234814)
    at Wo (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:156989)
    at Mc (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:216463)
    at https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:216374
    at N (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:233873)
    at MessagePort.x.port1.onmessage (https://dai-shi.github.io/excalidraw-claymate/static/js/2.a2abb0d8.chunk.js:2:232595)
x.port1.onmessage @ scheduler.production.min.js:12`

If you delete the arrow the error isn't thrown. It's reproducible if you load this file:

```
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://dai-shi.github.io",
  "elements": [
    {
      "type": "ellipse",
      "version": 128,
      "versionNonce": 2029613862,
      "isDeleted": false,
      "id": "1rLFt9A-wqxA0d2ViHBKe",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 552,
      "y": 242,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 100,
      "height": 100,
      "seed": 943671098,
      "groupIds": [],
      "strokeSharpness": "sharp",
      "boundElementIds": [
        "ISIo4859-suSdqTJugWr7"
      ]
    },
    {
      "type": "ellipse",
      "version": 41,
      "versionNonce": 559109779,
      "isDeleted": false,
      "id": "9cmB3R_ArsAYHbaZ50jfg",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 554,
      "y": 57,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 110,
      "height": 110,
      "seed": 1441705062,
      "groupIds": [],
      "strokeSharpness": "sharp",
      "boundElementIds": [
        "dbMbLUFDOvBSmscXXxbl9",
        "ISIo4859-suSdqTJugWr7"
      ]
    },
    {
      "type": "text",
      "version": 6,
      "versionNonce": 1434941286,
      "isDeleted": false,
      "id": "EUMw1dQloJumwrR8ZLfKS",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 579.5,
      "y": 99.5,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 59,
      "height": 25,
      "seed": 532150202,
      "groupIds": [],
      "strokeSharpness": "sharp",
      "boundElementIds": [],
      "fontSize": 20,
      "fontFamily": 1,
      "text": "Leads",
      "baseline": 18,
      "textAlign": "center",
      "verticalAlign": "middle"
    },
    {
      "type": "arrow",
      "version": 45,
      "versionNonce": 679508346,
      "isDeleted": false,
      "id": "ISIo4859-suSdqTJugWr7",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 606,
      "y": 175,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 0,
      "height": 61,
      "seed": 1164177510,
      "groupIds": [],
      "strokeSharpness": "round",
      "boundElementIds": [],
      "startBinding": {
        "elementId": "9cmB3R_ArsAYHbaZ50jfg",
        "focus": 0.05454545454545454,
        "gap": 8.071388124885921
      },
      "endBinding": {
        "elementId": "1rLFt9A-wqxA0d2ViHBKe",
        "focus": 0.08,
        "gap": 6.14267539047281
      },
      "points": [
        [
          0,
          0
        ],
        [
          0,
          61
        ]
      ],
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": "arrow"
    },
    {
      "type": "text",
      "version": 9,
      "versionNonce": 526626857,
      "isDeleted": false,
      "id": "6nf4gHPVYd6MFDOgFkiCj",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 563,
      "y": 279.5,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 78,
      "height": 25,
      "seed": 1242279974,
      "groupIds": [],
      "strokeSharpness": "sharp",
      "boundElementIds": [],
      "fontSize": 20,
      "fontFamily": 1,
      "text": "Content",
      "baseline": 18,
      "textAlign": "center",
      "verticalAlign": "top"
    }
  ],
  "appState": {
    "gridSize": null,
    "viewBackgroundColor": "#ffffff"
  }
}
```

**Comment by dai-shi** [comment]
Thanks for reporting.
I tried your file, and it seems to crash the app once, but then it's not reproducible again.
I wasn't able to check the console log when it crashes so it's not certain if the same error happened.
Is it stably reproducible on your end?

cc @grant-davidson can you try too if you are available?

**Comment by grant-davidson** [comment]
@dai-shi I can't reproduce this problem at all.  I always see the following without any errors
![image](https://user-images.githubusercontent.com/804371/124688571-1858e980-df2b-11eb-80a6-fd00179a94f5.png)

**Comment by dai-shi** [comment]
Thanks for checking.

Let's wait for @ChristianDavis to respond.

**Comment by ChristianDavis** [comment]
Sorry fellas. I can reproduce by loading the file on claymate, when trying it on excalidraw it just drops the arrow and swallows the error. So, something happened with that arrow, though I just connected it like normal. Here's a quick video:

https://www.loom.com/share/5bcb0427f883426aa0c0848d9d807b91

**Comment by ChristianDavis** [comment]
So this stems from that arrow being perfectly vertical, which gave it a width: 0, which at some point in excalidraw causes width:NanN, then when that goes through to `exportToCanvas`, canvas comes back with no width and no height. The exportToCanvas area of excalidraw was a little hard to figure out, but I'll open a PR that gets this project to the same behavior as excalidraw. Definitely originating on the excalidraw side though

**Comment by dai-shi** [comment]
Oh, nice catch!
