### ISSUE TITLE
404 error from GitHub pages on fonts and vendor.js

### ISSUE THREAD

**Issue by johnwebbcole** [dai-shi/excalidraw-claymate#5]
I'm getting a 404 error on a few files served from the `https://dai-shi.github.io/excalidraw-claymate/` link.

<img width="728" alt="Screen Shot 2020-12-15 at 9 25 05 AM" src="https://user-images.githubusercontent.com/230922/102356438-d0fd1280-3f72-11eb-9389-1c5db8546d56.png">

Looking in the GitHub pages branch, the files exist, so I'm unsure about the cause.

As a result, some of the fonts won't render, and I'm not sure what's in `vendor.js` :-) as the site seems to work otherwise.

Thx

**Comment by dai-shi** [comment]
Oh, no. Thanks for reporting.
It's trying to load `https://dai-shi.github.io/excalidraw-assets/FG_Virgil.woff2` instead of `https://dai-shi.github.io/excalidraw-claymate/excalidraw-assets/FG_Virgil.woff2`.

This issue is somewhat related with https://github.com/excalidraw/excalidraw/issues/2605

**Comment by ad1992** [comment]
@dai-shi as mentioned https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw#installation you will have to copy the folder `excalidraw-assets` to the path where you are serving your assets and it should be fine.

**Comment by dai-shi** [comment]
@ad1992 Please note the assets folder is placed alongside index.html. Hoewever, it's the link that points to the asset with the absolute path. How can you make it relative like `<font src="./excalidraw-assets/..."` ?

**Comment by ad1992** [comment]
@dai-shi looks like the assets are being served from https://dai-shi.github.io/excalidraw-claymate/ 
so the correct path would be https://dai-shi.github.io/excalidraw-claymate/excalidraw-assets/i18n-ca-ES-json.js instead of https://dai-shi.github.io/excalidraw-assets/i18n-ca-ES-json.js
If that's fixed it would work fine. Can you verify that once ?

**Comment by dai-shi** [comment]
@ad1992 Yes, that's the correct path. Is there an option to specify the prefix in `@excalidraw/excalidraw` package? I don't specify the excalidraw-assets path anywhere in my code. It works just fine with `yarn start` on localhost.

By the way, the code is pretty small for you to take a look as an application of your effort.

**Comment by ad1992** [comment]
@dai-shi no there is no option to specify the prefix and there shouldn't be any need as well as it should always append the `/excalidraw-assets` to whatever the base path is.  I am not sure if its an issue with `gh-pages`  as it's not adding the repo name in the URL, can you try setting the base URL or the base tag so all assets load from the correct path?

If it still doesn't work out let's sync up on discord. I will also try it out in one of my non-CRA apps.

**Comment by dai-shi** [comment]
> it should always append the /excalidraw-assets to whatever the base path is.

Does it take care of the base path? The index.html is served at https://dai-shi.github.io/excalidraw-claymate/

> can you try setting the base URL or the base tag so all assets load from the correct path?

Oh, do you mean `<base href="/excalidraw-claymate">` in the index.html?

**Comment by ad1992** [comment]
@dai-shi could you try out the version `aakansha-excalidraw@0.2.1-cdn` ?, I am serving the assets straight from the CDN so you need not copy the assets anymore.

**Comment by dai-shi** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/490574/102690053-24f34a00-4246-11eb-8ba5-7a5691ca9082.png">
Looks like working. Thanks!
