### ISSUE TITLE
Undo/Redo?

### ISSUE THREAD

**Issue by textreme** [dai-shi/excalidraw-claymate#82]
Undo/Redo does not work. Is this on purpose or a bug?

**Comment by dai-shi** [comment]
Do you mean undo like this?

https://github.com/dai-shi/excalidraw-claymate/assets/490574/9b6dfbf4-c9f5-4581-8f1b-db25715eda6e

Or, undo adding a scene?

**Comment by textreme** [comment]
Undo as in the video you shared.

**Comment by textreme** [comment]
Sorry, I just realized that you can only re-do within a scene and not across scenes.
